### PR TITLE
Extract Citations from PDF files 

### PR DESCRIPTION
**Pull request by abeltranandrade**
This function uses GROBID api in order to detect and extract citations from PDF files. It passes all CMD checks (except those already on the Rbuildignore but hopefully the GitHub CMD check will show they are addressed). There are also elementary tests that could be built upon in the future. 

This is the second merge request after the other for some reason, on my local machine, when fixing merge errors, I had a previous version of the main with the old gender function. I pulled the updated main and will try to fix the merge errors now and hopefully, it will be the most recent version.

### CODE REVIEW

**Comment by abeltranandrade** [comment]
I think bbr is a package that is not available in CRAN but that Lukas uses on his sample code that helps flatten a column list. We are able to install locally and work but its not budging with the github tests which makes sense

**Comment by abeltranandrade** [comment]
The bbr package is able to be installed through github [here ](https://metrumresearchgroup.github.io/bbr/) and Lukas uses it in team-resources/pdf_extraction Line 40 [here ](https://github.com/LukasWallrich/citationProfileR/blob/main/team-resources/pdf_extraction.R). 

I am looking and following [this now ](https://stackoverflow.com/questions/33764036/include-github-packages-as-imports-in-description)

**Comment by abeltranandrade** [comment]
Here is the documentation for the [dependencies from github](https://remotes.r-lib.org/articles/dependencies.html) but for some reason my checks still don't pass. If we fix this dependency thing all the errors will be fixed because the errors are coming from collapse_to_string not being found. It will be found if we are able to fix this.

**Comment by abeltranandrade** [comment]
These are other resources I am using such as [this ](https://stackoverflow.com/questions/29419776/r-package-dependencies-not-installed-from-additional-repositories)  or [this](https://remotes.r-lib.org/) that talk about additional_repositories but it seems to be more nuanced

**Comment by abeltranandrade** [comment]
My last attempt is trying to write an on load function that install the packages as[ seen here ](https://stackoverflow.com/questions/33764036/include-github-packages-as-imports-in-description) and I am following the way dylpr does it on zzz.R

**Comment by abeltranandrade** [comment]
@LukasWallrich I've tried so many things to make it so the CMD check to detect and import a dependency from github. 

As a summary, throughout the previous comments and commits I have used 3 main techniques: adding the remotes line in DESCRIPTION, adding an additional_dependencies line on DESCRIPTION, and writing a .on_load function that installs the packages using dev tools on install, yet nothing works. You can look back at my failed commits. 

The thing is that in your local machine if you install the package bbr through install_github and run the CMD, the errors are gone and only 3 non-critical notes show up, two related to the -on_load function (and run_on_load function call inside of it).

Screen Shot 2023-04-26 at 1 39 09 AM


For the demo on Thursday we need to merge this function into main so we can integrate it to our shiny. **As everything is working locally, just not on github CMD check, do you think we could merge the branch so we can work on the demo? Do you think you could help me figure out how to pass the github CMD check for dependencies that are not on CRAN?**

**Comment by LukasWallrich** [comment]
I'm somewhat confused about this - I have never seen the `bbr` package and do not see it in the file you link to (esp in line 40, which is a comment)? What are you using the package for?

**Comment by LukasWallrich** [comment]
Actually, I'm lying - I must have seen that package before as I copied the function from there, but did not remember the name at all - but I copied it over into my last project, so did not have to worry about dependencies. I would suggest you do the same here.


```r
# Copyright (c) 2020 Metrum Research Group under the MIT licence
# Retrieved from https://github.com/metrumresearchgroup/bbr/blob/main/LICENSE.md
collapse_to_string <- function(.data, ..., .sep = ", ") {
  checkmate::assert_scalar(.sep)

  cols <- tidyselect::eval_select(rlang::expr(c(...)), .data)

  # subset to only list cols and warn if passed any columns that are not lists
  valid_cols <- map_lgl(cols, ~ inherits(.data[[.x]], "list"))
  if (any(!valid_cols)) {
    bad_cols <- names(valid_cols)[!valid_cols]
    warning(glue("collapse_to_string() only works on list columns. The following columns are not lists and will be ignored: {paste(bad_cols, collapse = ', ')}"))
  }
  cols <- cols[valid_cols]

  # collapse together any lists of vectors
  .data %>%
    modify_at(.at = cols, .f = function(x) {
      map_chr(x, .f = function(.vec) {
        if (inherits(.vec, c("character", "numeric", "logical"))) {
          .vec <- paste0(.vec, collapse = .sep)
        } else if (is.null(.vec)) {
          .vec <- NA_character_
        } else {
          .vec <- paste(
            capture.output(dput(.vec)),
            collapse = ""
          )
        }
        return(.vec)
      })
    })
}

```

**Comment by abeltranandrade** [comment]
^^ I don't know how it just passed the CMD checks

**Comment by abeltranandrade** [comment]
Will still add the function into our file.

**Comment by abeltranandrade** [comment]
Just deleted the bbr dependency and CMD checks passed. We were ready to merge!

**Pull request merged**
